services:
  db:
    image: postgres:16-alpine
    container_name: architect_cv_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: architect_cv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
